name: Motor de Escala Anestesia

on:
  repository_dispatch:
    types: [gerar_proposta_escala, publicar_escala_final]

jobs:
  processar_escala:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Motor de Escala
        env:
          # Variáveis para o Python conseguir falar de volta com o Google
          GOOGLE_SHEET_ID: ${{ github.event.client_payload.id_coordenador }}
          FICHEIRO_OPERACIONAL_ID: ${{ github.event.client_payload.id_operacional }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python motor_escala.py
